## Descomentar para forzar el uso de python3
default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
    # -   id: debug-statements
    -   id: check-merge-conflict
    # Descomentar la siguiente linea para impedir commits a branch master (para repos donde usamos PR)
    # -   id: no-commit-to-branch
